export const phase7Messages = {
  ar: {
    registerTitle: "إنشاء حساب عميل", registerIntro: "أنشئ حساباً لمتابعة بياناتك وطلباتك.", registerName: "الاسم", registerEmail: "البريد الإلكتروني", registerPassword: "كلمة المرور (8 أحرف على الأقل)", registerConfirm: "تأكيد كلمة المرور", createAccount: "إنشاء حساب", hasAccount: "لديك حساب؟", noAccount: "ليس لديك حساب؟", login: "تسجيل الدخول", register: "إنشاء حساب",
    invalidName: "أدخل اسماً صالحاً لا يتجاوز 120 حرفاً.", invalidEmail: "أدخل بريداً إلكترونياً صالحاً.", emailAlreadyRegistered: "هذا البريد الإلكتروني مسجل بالفعل. سجّل الدخول أو استخدم بريداً آخر.", invalidPassword: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.", passwordMismatch: "كلمتا المرور غير متطابقتين.", registrationFailed: "حدث خطأ غير متوقع أثناء إنشاء الحساب. حاول مرة أخرى لاحقاً.", registrationUnavailable: "تعذر الاتصال بالخادم حالياً. حاول مرة أخرى بعد قليل.", registered: "تم إنشاء الحساب. يمكنك تسجيل الدخول الآن.",
    accountTitle: "حسابي", signOut: "تسجيل الخروج", profile: "الملف الشخصي", shoppingAccount: "حساب التسوق", myOrders: "طلباتي", addresses: "عناويني", editNameHint: "يمكنك تعديل اسمك؛ البريد الإلكتروني ثابت لحماية هوية الدخول.", saveName: "حفظ الاسم", profileUpdated: "تم تحديث الاسم.", loginToAccount: "يرجى تسجيل الدخول لاستخدام حسابك.", loginToAddresses: "يرجى تسجيل الدخول لإدارة عناوينك.", invalidProfile: "أدخل اسماً صالحاً لا يتجاوز 120 حرفاً.", profileSaveFailed: "تعذر حفظ الملف الشخصي حالياً.",
    addressesTitle: "عناويني", noAddresses: "لا توجد عناوين محفوظة بعد. أضف عنوانك الأول أدناه.", addAddress: "إضافة عنوان", editAddress: "تعديل العنوان", saveAddress: "حفظ التعديل", addressSaved: "تم تحديث العنوان.", addressAdded: "تمت إضافة العنوان.", defaultAddress: "افتراضي", setDefault: "تعيين افتراضي", delete: "حذف", addressMissing: "العنوان غير موجود.", addressSaveInvalid: "تحقق من الاسم والهاتف والعنوان والمدينة.", addressSaveFailed: "تعذر حفظ العنوان. تحقق من البيانات وحاول مرة أخرى.", defaultFailed: "تعذر تعيين العنوان الافتراضي.", defaultSaved: "تم تعيين العنوان الافتراضي.", deleteFailed: "تعذر حذف العنوان.", addressDeleted: "تم حذف العنوان.", invalidPhone: "أدخل رقم هاتف صالحاً.", invalidAddress: "أدخل عنواناً صالحاً.", invalidCity: "أدخل مدينة صالحة.", tooLong: "النص أطول من الحد المسموح.",
    fullName: "الاسم الكامل", phone: "الهاتف", addressLine: "العنوان", city: "المدينة", postalCode: "الرمز البريدي (اختياري)", notes: "ملاحظات (اختياري)", makeDefault: "جعله العنوان الافتراضي",
    settingsTitle: "إعدادات المتجر", settingsDescription: "بيانات المتجر والعملة الافتراضية المستخدمة في الأسعار الجديدة.", storeName: "اسم المتجر", storeDescription: "وصف المتجر", currency: "العملة", chooseCurrency: "اختر العملة", contactPhone: "هاتف المتجر", storeEmail: "البريد الإلكتروني", storeAddress: "العنوان", defaultLocale: "اللغة الافتراضية", Arabic: "العربية", storeActive: "المتجر متاح للعملاء", saveSettings: "حفظ الإعدادات", settingsHint: "اللغة العربية هي اللغة المتاحة حالياً. لا يتم تخزين ملفات الصور هنا.", settingsUnauthorized: "لا تملك صلاحية لتعديل إعدادات المتجر.", settingsInvalid: "تحقق من الاسم والعملة والبريد الإلكتروني وبقية البيانات.", settingsFailed: "تعذر حفظ الإعدادات حالياً.", settingsSaved: "تم حفظ إعدادات المتجر.",
    skuManagement: "المتغيرات والمخزون", price: "السعر", stock: "المخزون", variantJson: "خيارات المتغير بصيغة JSON", variantActive: "المتغير نشط وقابل للشراء", saveVariant: "حفظ المتغير", addVariant: "إضافة متغير", noVariants: "لا توجد متغيرات بعد.", skuInvalid: "تحقق من السعر والمخزون وخيارات المنتج.", skuUnauthorized: "لا تملك صلاحية إدارة المنتجات.", skuDuplicate: "حدث تعارض أثناء حفظ المتغير.", skuSaveFailed: "تعذر حفظ المتغير. تحقق من البيانات.", skuSaved: "تم حفظ المتغير.",
    productImages: "صور المنتج", imageHttps: "ملف الصورة", imageAlt: "النص البديل", saveImage: "حفظ الصورة", addImage: "إضافة صورة", primaryImage: "الصورة الرئيسية", imageNumber: "صورة {number}", moveUp: "تحريك للأعلى", moveDown: "تحريك للأسفل", setPrimary: "تعيين كصورة رئيسية", noImages: "لم تتم إضافة صور للمنتج بعد.", imageUnauthorized: "لا تملك صلاحية إدارة الصور.", imageInvalid: "اختر صورة صالحة بصيغة JPG أو PNG أو WEBP.", imageSaveFailed: "تعذر حفظ الصورة. تحقق من صلاحية الصورة وحدّ الصور.", imageSaved: "تم حفظ الصورة.", imageMissing: "الصورة غير موجودة.", imageDeleteFailed: "تعذر حذف الصورة.", imageDeleted: "تم حذف الصورة.", imagePrimaryFailed: "تعذر تغيير الصورة الرئيسية.", imagePrimarySaved: "تم تعيين الصورة الرئيسية.", imageMoveFailed: "تعذر تغيير ترتيب الصورة.", imageMoved: "تم تغيير ترتيب الصور.", imageUnavailable: "الصورة غير متاحة",
    savedAddress: "عنوان محفوظ", enterOtherAddress: "إدخال عنوان آخر", defaultLabel: "افتراضي", currencySAR: "ريال سعودي", currencyUSD: "دولار أمريكي", currencyEUR: "يورو", currencyILS: "شيكل", currencyJOD: "دينار أردني",
  },
} as const;
